name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dockerfile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cabal: ["3.10.3"]
        ghc: ["9.4.8", "9.6.7", "9.8.4", "9.10.2", "9.12.2"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build container
        run: docker build -t psephology --build-arg GHC_VERSION=${{ matrix.ghc }} .
      - name: Run tests
        run: docker run --rm -t psephology

      - name: Run examples
        run: |
          cabal run example-generate-blt
          cabal run example-georgia-redistricting
          cabal run example-mrp
          cabal run example-sample-parliament
