name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dockerfile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cabal: ["3.10.3"]
        ghc: ["9.4.8", "9.6.7", "9.8.4", "9.10.2", "9.12.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build container
        run: docker build -t psephology --build-arg GHC_VERSION=${{ matrix.ghc }} .
      - name: Run tests
        run: docker run --rm -t psephology
      - name: Run examples
        run: |
          docker run --rm -t psephology cabal run example-generate-blt
          docker run --rm -t psephology cabal run example-georgia-redistricting
          docker run --rm -t psephology cabal run example-mrp
          docker run --rm -t psephology cabal run example-sample-parliament
