name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cabal: ["3.10.3"]
        ghc: ["9.4.8", "9.6.7", "9.8.4", "9.10.2", "9.12.2"]

    steps:
      - name: Install GHC
        run: ghcup install ghc "$HCVER"
        env:
          HCVER: ${{ matrix.ghc }}

      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
          
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: Run tests
        run: cabal run tests
      - name: Run examples
        run: |
          cabal run example-generate-blt
          cabal run example-georgia-redistricting
          cabal run example-sample-parliament
      - name: Build docs
        run: ./docs.sh
